spring:
  data:
    mongodb:
      host: localhost # \u4E3B\u673A\u5730\u5740
      port: 27017 # \u7AEF\u53E3
      username: root # \u7528\u6237\u540D
      password: "123456" # \u5BC6\u7801
      database: test # \u6570\u636E\u5E93
      authentication-database: admin # \u8BA4\u8BC1\u6570\u636E\u5E93