spring:
  data:
    mongodb:
      host: localhost # 主机
      port: 27017 # 端口
      username: root # 用户名
      password: "123456" # 密码
      database: test # 数据库
      authentication-database: admin # 认证数据库