spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true # \u5141\u8BB8\u8FDC\u7A0B\u8BBF\u95EE
        web-admin-password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
