server:
  port: 80

spring:
  profiles:
    active: @spring.profiles.active@
  datasource: # 数据源的配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://@mysql.ip@:@mysql.port@/ssm?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: @mysql.username@
    password: @mysql.password@
