# \u516C\u5171\u914D\u7F6E
server:
  port: 80

spring:
  profiles:
    active: dev # \u6FC0\u6D3B\u6307\u5B9A\u7684\u73AF\u5883
---
# \u5F00\u53D1\u73AF\u5883
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 81

---
# \u6D4B\u8BD5\u73AF\u5883
spring:
  config:
    activate:
      on-profile: test

server:
  port: 82

---
# \u751F\u4EA7\u73AF\u5883
spring:
  config:
    activate:
      on-profile: test

server:
  port: 83